CREATE TABLE BOARD(
					CONTENT_ID INTEGER(8) NOT NULL PRIMARY KEY,
					PASSWORD VARCHAR(20) NOT NULL,
					SUBJECT VARCHAR(20) NOT NULL,
					CONTENT VARCHAR(500),
					WRITE_DATE DATE,
					WRITE_TIME TIME,
					READ_CNT INTEGER(8));